---
defaults:
  - /schema/dm: ecoacoustics
  - _self_
train_batch_size: 1
eval_batch_size: null
val_prop: 0.2
test_prop: 0.2
num_workers: 0
seed: 47
persist_workers: false
pin_memory: true
stratified_sampling: false
instance_weighting: false
training_mode: epoch
root: /srv/galene0/shared/data/conduit/
train_transforms:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: conduit.transforms.LogMelSpectrogram
      sample_rate: 16_000
      n_fft: 400
      win_length: 400
      hop_length: 160
      f_min: 125.0
      f_max: 7_500.0
      pad: 0
      n_mels: 64
      window_fn: null # default is torch.hann_window
      power: 2.0
      normalized: false
      wkwargs: null
      center: true
      pad_mode: "reflect"
      onesided: true
      norm: null
      mel_scale: "htk"
      log_offset: 0.01
    - _target_: conduit.transforms.Framing
test_transforms:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: conduit.transforms.LogMelSpectrogram
      sample_rate: 16_000
      n_fft: 400
      win_length: 400
      hop_length: 160
      f_min: 125.0
      f_max: 7_500.0
      pad: 0
      n_mels: 64
      window_fn: null # default is torch.hann_window
      power: 2.0
      normalized: false
      wkwargs: null
      center: true
      pad_mode: "reflect"
      onesided: true
      norm: null
      mel_scale: "htk"
      log_offset: 0.01
    - _target_: conduit.transforms.Framing
segment_len: 60
sample_rate: 16_000
target_attrs: [habitat]
